services:
  db1:
    image: mongo
    container_name: mongo1
    ports:
      - "27017:27017"
    networks:
      - mongo-cluster
    volumes:
      - ./data1:/data/db
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

  db2:
    image: mongo
    container_name: mongo2
    ports:
      - "27018:27017"
    networks:
      - mongo-cluster
    volumes:
      - ./data2:/data/db
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

  db3:
    image: mongo
    container_name: mongo3
    ports:
      - "27019:27017"
    networks:
      - mongo-cluster
    volumes:
      - ./data3:/data/db
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

networks:
  mongo-cluster:
    driver: bridge

